### ISSUE TITLE
No such file in directory  'alexandrtovmach.com\node_modules\node-sass\vendor'

### ISSUE THREAD

**Issue by DuudeXX8** [alexandrtovmach/alexandrtovmach.com#9]
After clone project and install npm modules I get an error.

**Error: ENOENT: no such file or directory, scandir  \alexandrtovmach.com\node_modules\node-sass\vendor'**

Please add a vendor folder.Ty in advance.

**Comment by alexandrtovmach** [comment]
you need to add `SASS_PATH=src/styles` to _.env_ file in root of project
